### PR TITLE
Use template strings for better code legibility

### PR DESCRIPTION
**Pull request by joao-alberto**

### CODE REVIEW

**Comment by MatejMecka** [comment]
Hey there! Circle Ci is complaining that it has a failing test case. Do you like me to edit your file or are you going to resolve the issue?

**Comment by joao-alberto** [comment]
The problem was probably fixed by #15 
Can you rebuild again on CI to verify that?

screenshot from 2017-10-23 17-21-58

**Comment by MatejMecka** [comment]
just rebuilt it. Works for me.

https://circleci.com/gh/MatejMecka/HacktoberfestStats/6

**Comment by MatejMecka** [comment]
I'll merge it tommorow and I'll fix the issue. Thanks for the pull request

**Pull request closed without merging**
